<?php

/**
 * @file
 * Contains argue_proscons.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function argue_proscons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the argue_proscons module.
    case 'help.page.argue_proscons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a subentity list with arguments for a rule represented by a node.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function argue_proscons_theme() {
  return [
    'argument' => [
      'render element' => 'content',
    ],
    // @todo Can this be removed?? Can better be done by theme hook suggestions.
    'argument__teaser' => [
      'render element' => 'content',
    ],
    // @todo Can this be removed?? Can better be done by theme hook suggestions.
    'argument__teaser_pro' => [
      'render element' => 'content',
    ],
    'change_request__list_item' => [
      'variables' => [
        'attributes' => NULL,
        'url' => NULL,
        'label' => NULL,
        'status' => NULL,
        'status_literal' => NULL,
      ],
    ],
    'argue_proscons' => [
      'render element' => 'children',
    ],
    'argue_chip_set' => [
      'render element' => 'children',
    ],
    'argue_chip' => [
      'variables' => [
        'attributes' => NULL,
        'icon_before' => NULL,
        'text' => '',
        'icon_after' => NULL,
      ],
    ],
  ];
}


/**
 * Implements hook_theme_suggestions_HOOK().
 */
function argue_proscons_theme_suggestions_argument(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['content']['#view_mode'], '.', '_');
  $suggestions[] = 'argument__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * The canonical view of arguments will be redirected to its parent node.
 *
 * @param array $build
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 * @param $view_mode
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 * @throws \Drupal\Core\TypedData\Exception\MissingDataException
 */
function argue_proscons_argument_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if($view_mode == 'full' && \Drupal::routeMatch()->getRouteName() == 'entity.argument.canonical') {
    $parent = $entity->get("reference_id")->referencedEntities();
    /** @var \Drupal\node\NodeInterface $parent */
    if($parent = reset($parent)) {
      $url = $parent->toUrl();
      $url->setOption('fragment' ,'argument_' . $entity->id());
      $url = (string) $url->toString();
      $response = new RedirectResponse($url, 301);
      $response->send();
      exit();
    }
  } else {
    // Set id to scroll to the id.
    if(!isset($build['attributes'])) {
      $build['#attributes'] = new \Drupal\Core\Template\Attribute();
    }
    $arg_type = $entity->getTypeStr();
    $build['#attributes']->setAttribute('id', 'argument_' . $entity->id());
    $build['#attributes']->addClass('argument-' . $arg_type);
    $build['argument_type'] = ['#markup' => $arg_type];
  }

  // Attach chips for hidden references.
  $build['chips'] = [
    '#theme' => 'argue_chip_set',
    '#attributes' => ['class' => ['huhu']],
  ];

  // Icon map used for chips. If not set, the entity type id is used.
  $chip_icon_map = ['patch' => 'change_request'];
  /**
   * Loop over fields and append the chips to the chip set.
   *
   * @var string $field_name
   * @var Drupal\Core\Field\FieldDefinitionInterface $field_definition
   */
  foreach ($entity->getFieldDefinitions() as $field_name => $field_definition) {
    if (isset ($build[$field_name])) {
      if ($field_definition->getType() == 'comment') {
        $field_comment = $entity->get($field_name);
        if ($field_comment instanceof \Drupal\comment\CommentFieldItemList) {
          $build["chips"][] = [
            '#theme' => 'argue_chip',
            '#attributes' => ['title' => t('Number of comments on this argument.')],
            '#icon_before' => 'comments',
            '#text' => $field_comment->first()->comment_count,
          ];
        }
      } elseif ($field_definition->getType() == 'entity_reference') {
        $target_type = $field_definition->getItemDefinition()->getSetting('target_type');
        $is_multiple_field = (1 !== $field_definition->getFieldStorageDefinition()->getCardinality());
        if ($is_multiple_field) {
          $build["chips"][] = [
            '#theme' => 'argue_chip',
            '#attributes' => ['title' => t('Number of comments on this argument.')],
            '#icon_before' => $chip_icon_map[$target_type] ?? $target_type,
            '#text' => $entity->get($field_name)->count(),
          ];
        }
      }
    }
  }

  // Attach the rate_vote_widget.
  // @todo Replace by own rate widget.
  $type = $entity->getEntityTypeId();
  $bundle = $entity->bundle();

  $view_string = "{$type}__{$bundle}__{$view_mode}";

  $show = [
    'argument__argument__teaser',
    'argument__argument__teaser_pro',
  ];

  if (in_array($view_string, $show) && $widget_config = $display->getComponent('rate_vote_widget')) {
    $vote_widget_service = \Drupal::service('rate.entity.vote_widget');
    $vote_widget = $vote_widget_service->buildRateVotingWidget($entity->id(), $type, $bundle);

    if (isset($vote_widget['rate_vote_widget'])) {
      $vote_widget['rate_vote_widget']['#weight'] = $widget_config['weight'] ?? 2;
    }

    // add library
    if (!isset($vote_widget['#attached']['library'])) {
      $vote_widget['#attached']['library'] = [];
    }
    $vote_widget['#attached']['library'][] = 'argue_proscons/proscons.teaser';
    $vote_widget['#group'] = 'voting';

    // move voting widget to own region.
    $build['voting'] = [
      '#type' => 'container',
      '#weight' => 10,
      '#attributes' => ['class' => ['voting']],
      '#tree' => TRUE,
      '#access' => TRUE,
      'votingapi_links' => $vote_widget,
    ];
  }
}
